In [1]:
import pandas as pd
import numpy as np

In [32]:
data = pd.read_csv('./data/train.csv')
data.head()

,时间,小区名,小区房屋出租数量,楼层,总楼层,房屋面积,房屋朝向,居住状态,卧室数量,厅的数量,卫的数量,出租方式,区,位置,地铁线路,地铁站点,距离,装修情况,月租金
0,1,3072,0.128906,2,0.236364,0.008628,东南,NaN,1,1,1,NaN,11.0,118.0,2.0,40.0,0.764167,NaN,5.602716
1,1,3152,0.132812,1,0.381818,0.017046,东,NaN,1,0,0,NaN,10.0,100.0,4.0,58.0,0.709167,NaN,16.977929
2,1,5575,0.042969,0,0.290909,0.010593,东南,NaN,2,1,2,NaN,12.0,130.0,5.0,37.0,0.572500,NaN,8.998302
3,1,3103,0.085938,2,0.581818,0.019199,南,NaN,3,2,2,NaN,7.0,90.0,2.0,63.0,0.658333,NaN,5.602716
4,1,5182,0.214844,0,0.545455,0.010427,东北,NaN,2,1,1,NaN,3.0,31.0,NaN,NaN,NaN,NaN,7.300509

In [33]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 196539 entries, 0 to 196538
Data columns (total 19 columns):
时间          196539 non-null int64
小区名         196539 non-null int64
小区房屋出租数量    195538 non-null float64
楼层          196539 non-null int64
总楼层         196539 non-null float64
房屋面积        196539 non-null float64
房屋朝向        196539 non-null object
居住状态        20138 non-null float64
卧室数量        196539 non-null int64
厅的数量        196539 non-null int64
卫的数量        196539 non-null int64
出租方式        24230 non-null float64
区           196508 non-null float64
位置          196508 non-null float64
地铁线路        91778 non-null float64
地铁站点        91778 non-null float64
距离          91778 non-null float64
装修情况        18492 non-null float64
月租金         196539 non-null float64
dtypes: float64(12), int64(6), object(1)
memory usage: 28.5+ MB

In [34]:
data.describe()

,时间,小区名,小区房屋出租数量,楼层,总楼层,房屋面积,居住状态,卧室数量,厅的数量,卫的数量,出租方式,区,位置,地铁线路,地铁站点,距离,装修情况,月租金
count,196539.000000,196539.000000,195538.000000,196539.000000,196539.000000,196539.000000,20138.000000,196539.000000,196539.000000,196539.000000,24230.000000,196508.000000,196508.000000,91778.000000,91778.000000,91778.000000,18492.000000,196539.000000
mean,2.115229,3224.116562,0.124151,0.955449,0.408711,0.013139,2.725196,2.236635,1.299625,1.223818,0.900289,7.905139,67.945982,3.284850,57.493735,0.551202,3.589228,7.949313
std,0.786980,2023.073726,0.133299,0.851511,0.183100,0.008104,0.667763,0.896961,0.613169,0.487234,0.299621,4.025696,43.522394,1.477147,35.191414,0.247268,1.996912,6.310609
min,1.000000,0.000000,0.007812,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.001667,1.000000,0.000000
25%,1.000000,1388.000000,0.039062,0.000000,0.290909,0.009268,3.000000,2.000000,1.000000,1.000000,1.000000,4.000000,33.000000,2.000000,23.000000,0.356667,2.000000,4.923599
50%,2.000000,3086.000000,0.082031,1.000000,0.418182,0.012910,3.000000,2.000000,1.000000,1.000000,1.000000,9.000000,61.000000,4.000000,59.000000,0.554167,2.000000,6.621392
75%,3.000000,5199.000000,0.160156,2.000000,0.563636,0.014896,3.000000,3.000000,2.000000,1.000000,1.000000,11.000000,103.000000,5.000000,87.000000,0.745833,6.000000,8.998302
max,3.000000,6627.000000,1.000000,2.000000,1.000000,1.000000,3.000000,11.000000,8.000000,8.000000,1.000000,14.000000,152.000000,5.000000,119.000000,1.000000,6.000000,100.000000

In [35]:
import matplotlib.pyplot as plt
import seaborn as sns

In [36]:
data.isnull().sum()

时间               0
小区名              0
小区房屋出租数量      1001
楼层               0
总楼层              0
房屋面积             0
房屋朝向             0
居住状态        176401
卧室数量             0
厅的数量             0
卫的数量             0
出租方式        172309
区               31
位置              31
地铁线路        104761
地铁站点        104761
距离          104761
装修情况        178047
月租金              0
dtype: int64

In [37]:
data = data.drop(['居住状态','出租方式','装修情况'],axis=1)

In [38]:
data.head()

,时间,小区名,小区房屋出租数量,楼层,总楼层,房屋面积,房屋朝向,卧室数量,厅的数量,卫的数量,区,位置,地铁线路,地铁站点,距离,月租金
0,1,3072,0.128906,2,0.236364,0.008628,东南,1,1,1,11.0,118.0,2.0,40.0,0.764167,5.602716
1,1,3152,0.132812,1,0.381818,0.017046,东,1,0,0,10.0,100.0,4.0,58.0,0.709167,16.977929
2,1,5575,0.042969,0,0.290909,0.010593,东南,2,1,2,12.0,130.0,5.0,37.0,0.572500,8.998302
3,1,3103,0.085938,2,0.581818,0.019199,南,3,2,2,7.0,90.0,2.0,63.0,0.658333,5.602716
4,1,5182,0.214844,0,0.545455,0.010427,东北,2,1,1,3.0,31.0,NaN,NaN,NaN,7.300509

In [39]:
data.drop(['房屋朝向'],axis=1,inplace=True)

In [40]:
data.head()

,时间,小区名,小区房屋出租数量,楼层,总楼层,房屋面积,卧室数量,厅的数量,卫的数量,区,位置,地铁线路,地铁站点,距离,月租金
0,1,3072,0.128906,2,0.236364,0.008628,1,1,1,11.0,118.0,2.0,40.0,0.764167,5.602716
1,1,3152,0.132812,1,0.381818,0.017046,1,0,0,10.0,100.0,4.0,58.0,0.709167,16.977929
2,1,5575,0.042969,0,0.290909,0.010593,2,1,2,12.0,130.0,5.0,37.0,0.572500,8.998302
3,1,3103,0.085938,2,0.581818,0.019199,3,2,2,7.0,90.0,2.0,63.0,0.658333,5.602716
4,1,5182,0.214844,0,0.545455,0.010427,2,1,1,3.0,31.0,NaN,NaN,NaN,7.300509

In [41]:
data.corr().sort_values('月租金',ascending=False)

,时间,小区名,小区房屋出租数量,楼层,总楼层,房屋面积,卧室数量,厅的数量,卫的数量,区,位置,地铁线路,地铁站点,距离,月租金
月租金,-0.014485,0.007568,0.011822,0.009495,0.139803,0.440718,0.315892,0.221741,0.423756,0.146881,0.006541,0.187766,0.019662,-0.075449,1.000000
房屋面积,-0.004721,-0.024287,-0.118545,0.015302,-0.023699,1.000000,0.496768,0.369583,0.485070,-0.020327,0.037643,0.031685,-0.012102,0.030277,0.440718
卫的数量,0.002086,-0.036798,-0.081385,0.023813,0.000035,0.485070,0.569449,0.369906,1.000000,-0.004801,0.011516,0.051845,-0.049484,0.044303,0.423756
卧室数量,0.019267,-0.043331,-0.143162,0.042156,0.038335,0.496768,1.000000,0.492110,0.569449,-0.051460,-0.008902,-0.009134,-0.114370,0.081286,0.315892
厅的数量,-0.007166,-0.056097,-0.105523,0.025625,0.028477,0.369583,0.492110,1.000000,0.369906,-0.062560,-0.007798,-0.023647,-0.035749,0.096339,0.221741
地铁线路,0.056832,0.015961,0.276701,0.001041,0.251467,0.031685,-0.009134,-0.023647,0.051845,0.146703,0.056357,1.000000,-0.093912,-0.118322,0.187766
区,-0.013044,-0.013252,0.059932,-0.001279,0.042095,-0.020327,-0.051460,-0.062560,-0.004801,1.000000,0.022993,0.146703,0.037317,-0.061235,0.146881
总楼层,0.028270,0.003401,0.306333,0.026950,1.000000,-0.023699,0.038335,0.028477,0.000035,0.042095,-0.142422,0.251467,-0.171196,-0.113633,0.139803
地铁站点,-0.018956,0.048293,0.100259,-0.028365,-0.171196,-0.012102,-0.114370,-0.035749,-0.049484,0.037317,0.147762,-0.093912,1.000000,0.067468,0.019662
小区房屋出租数量,0.061631,0.079298,1.000000,-0.005990,0.306333,-0.118545,-0.143162,-0.105523,-0.081385,0.059932,-0.075279,0.276701,0.100259,-0.045001,0.011822
楼层,-0.002012,-0.002413,-0.005990,1.000000,0.026950,0.015302,0.042156,0.025625,0.023813,-0.001279,-0.012153,0.001041,-0.028365,-0.005451,0.009495
小区名,-0.011681,1.000000,0.079298,-0.002413,0.003401,-0.024287,-0.043331,-0.056097,-0.036798,-0.013252,0.025419,0.015961,0.048293,-0.013597,0.007568
位置,0.005666,0.025419,-0.075279,-0.012153,-0.142422,0.037643,-0.008902,-0.007798,0.011516,0.022993,1.000000,0.056357,0.147762,0.068591,0.006541
时间,1.000000,-0.011681,0.061631,-0.002012,0.028270,-0.004721,0.019267,-0.007166,0.002086,-0.013044,0.005666,0.056832,-0.018956,0.000383,-0.014485
距离,0.000383,-0.013597,-0.045001,-0.005451,-0.113633,0.030277,0.081286,0.096339,0.044303,-0.061235,0.068591,-0.118322,0.067468,1.000000,-0.075449

In [42]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 196539 entries, 0 to 196538
Data columns (total 15 columns):
时间          196539 non-null int64
小区名         196539 non-null int64
小区房屋出租数量    195538 non-null float64
楼层          196539 non-null int64
总楼层         196539 non-null float64
房屋面积        196539 non-null float64
卧室数量        196539 non-null int64
厅的数量        196539 non-null int64
卫的数量        196539 non-null int64
区           196508 non-null float64
位置          196508 non-null float64
地铁线路        91778 non-null float64
地铁站点        91778 non-null float64
距离          91778 non-null float64
月租金         196539 non-null float64
dtypes: float64(9), int64(6)
memory usage: 22.5 MB

In [43]:
data['小区房屋出租数量'].isnull()

0         False
1         False
2         False
3         False
4         False
          ...
196534    False
196535    False
196536    False
196537    False
196538    False
Name: 小区房屋出租数量, Length: 196539, dtype: bool

In [44]:
data=data[data['小区房屋出租数量'].isnull()==False]

In [45]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 195538 entries, 0 to 196538
Data columns (total 15 columns):
时间          195538 non-null int64
小区名         195538 non-null int64
小区房屋出租数量    195538 non-null float64
楼层          195538 non-null int64
总楼层         195538 non-null float64
房屋面积        195538 non-null float64
卧室数量        195538 non-null int64
厅的数量        195538 non-null int64
卫的数量        195538 non-null int64
区           195508 non-null float64
位置          195508 non-null float64
地铁线路        91289 non-null float64
地铁站点        91289 non-null float64
距离          91289 non-null float64
月租金         195538 non-null float64
dtypes: float64(9), int64(6)
memory usage: 23.9 MB

In [46]:
data=data[data['区'].isnull()==False]

In [47]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 195508 entries, 0 to 196538
Data columns (total 15 columns):
时间          195508 non-null int64
小区名         195508 non-null int64
小区房屋出租数量    195508 non-null float64
楼层          195508 non-null int64
总楼层         195508 non-null float64
房屋面积        195508 non-null float64
卧室数量        195508 non-null int64
厅的数量        195508 non-null int64
卫的数量        195508 non-null int64
区           195508 non-null float64
位置          195508 non-null float64
地铁线路        91273 non-null float64
地铁站点        91273 non-null float64
距离          91273 non-null float64
月租金         195508 non-null float64
dtypes: float64(9), int64(6)
memory usage: 23.9 MB

In [48]:
data=data.fillna(0)

In [49]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 195508 entries, 0 to 196538
Data columns (total 15 columns):
时间          195508 non-null int64
小区名         195508 non-null int64
小区房屋出租数量    195508 non-null float64
楼层          195508 non-null int64
总楼层         195508 non-null float64
房屋面积        195508 non-null float64
卧室数量        195508 non-null int64
厅的数量        195508 non-null int64
卫的数量        195508 non-null int64
区           195508 non-null float64
位置          195508 non-null float64
地铁线路        195508 non-null float64
地铁站点        195508 non-null float64
距离          195508 non-null float64
月租金         195508 non-null float64
dtypes: float64(9), int64(6)
memory usage: 23.9 MB

In [50]:
data.corr().sort_values('月租金',ascending=False)

,时间,小区名,小区房屋出租数量,楼层,总楼层,房屋面积,卧室数量,厅的数量,卫的数量,区,位置,地铁线路,地铁站点,距离,月租金
月租金,-0.013914,0.007759,0.011813,0.009694,0.139511,0.439952,0.315561,0.221743,0.423384,0.146882,0.006595,0.220034,0.138799,0.111975,1.000000
房屋面积,-0.005025,-0.024333,-0.118547,0.015347,-0.023452,1.000000,0.495976,0.369227,0.484424,-0.020259,0.037833,0.012974,-0.007646,0.012183,0.439952
卫的数量,0.002178,-0.036826,-0.081386,0.024089,-0.000160,0.484424,0.569431,0.369989,1.000000,-0.004949,0.011719,0.001129,-0.037859,-0.001711,0.423384
卧室数量,0.019027,-0.043042,-0.143170,0.042328,0.038886,0.495976,1.000000,0.492196,0.569431,-0.051495,-0.008903,-0.091367,-0.130302,-0.058613,0.315561
厅的数量,-0.007384,-0.056084,-0.105529,0.025710,0.029059,0.369227,0.492196,1.000000,0.369989,-0.062402,-0.007857,-0.097784,-0.096199,-0.055142,0.221743
地铁线路,0.019434,0.024283,0.092696,-0.007290,0.015425,0.012974,-0.091367,-0.097784,0.001129,0.138965,0.112218,1.000000,0.620832,0.692923,0.220034
区,-0.012304,-0.013256,0.059932,-0.001257,0.041619,-0.020259,-0.051495,-0.062402,-0.004949,1.000000,0.022310,0.138965,0.098138,0.074596,0.146882
总楼层,0.030606,0.003887,0.306323,0.027267,1.000000,-0.023452,0.038886,0.029059,-0.000160,0.041619,-0.142445,0.015425,-0.152125,-0.123783,0.139511
地铁站点,-0.009629,0.038031,0.031294,-0.019623,-0.152125,-0.007646,-0.130302,-0.096199,-0.037859,0.098138,0.147073,0.620832,1.000000,0.675504,0.138799
距离,-0.000992,0.013779,-0.040166,-0.009537,-0.123783,0.012183,-0.058613,-0.055142,-0.001711,0.074596,0.116169,0.692923,0.675504,1.000000,0.111975
小区房屋出租数量,0.061643,0.079301,1.000000,-0.005988,0.306323,-0.118547,-0.143170,-0.105529,-0.081386,0.059932,-0.075279,0.092696,0.031294,-0.040166,0.011813
楼层,-0.002286,-0.002048,-0.005988,1.000000,0.027267,0.015347,0.042328,0.025710,0.024089,-0.001257,-0.012200,-0.007290,-0.019623,-0.009537,0.009694
小区名,-0.011716,1.000000,0.079301,-0.002048,0.003887,-0.024333,-0.043042,-0.056084,-0.036826,-0.013256,0.025617,0.024283,0.038031,0.013779,0.007759
位置,0.005529,0.025617,-0.075279,-0.012200,-0.142445,0.037833,-0.008903,-0.007857,0.011719,0.022310,1.000000,0.112218,0.147073,0.116169,0.006595
时间,1.000000,-0.011716,0.061643,-0.002286,0.030606,-0.005025,0.019027,-0.007384,0.002178,-0.012304,0.005529,0.019434,-0.009629,-0.000992,-0.013914

In [51]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [52]:
# lr_model = LinearRegression()
X=data.iloc[:,:-1]
y=data['月租金']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=42)

In [53]:
X_train.shape

(136855, 14)

In [54]:
y_train.shape

(136855,)

In [55]:
from sklearn.ensemble import RandomForestRegressor
rfr_model = RandomForestRegressor(max_depth=10,n_estimators=10)
rfr_model.fit(X_train,y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=10, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=10, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

In [56]:
y_predict=rfr_model.predict(X_test)

In [57]:
type(y_predict)

numpy.ndarray

In [58]:
type(y_test)

pandas.core.series.Series

In [59]:
rmse=((y_predict-y_test)**2).mean()**0.5
rmse

2.951806816303515